32/usr/scripts/updates-gui, 64/usr/scripts/updates-gui
A little notification touch - After checking for updates with Lite Install Updates and finding new updates but cancelling instead of updating... this notification will be displayed.
=> Small notification touch

32/usr/bin/lite-software, 32/usr/scripts/updates-gui, 64/usr/bin/lite-software, 64/usr/scripts/updates-gui, README.md
- Loop Install/Remove Software dialogues
- Rename "Cancel" button to "Back to Task Selector"
- Other minor wording updates
- Show only Not Installed applications in the Installation section
https://www.linuxliteos.com/forums/developers-corner/update-for-lite-software-logic/msg27790/#msg27790
=> Loop implemented - minor wording changes

32/usr/bin/lite-software, 64/usr/bin/lite-software
https://www.linuxliteos.com/forums/developers-corner/update-for-lite-software-logic/msg27808/#msg27808
=> loop adjustments

DEBIAN/postinst
https://www.linuxliteos.com/forums/other/updating-problems/msg28273/?top
icseen#msg28273
=> forum reported fix

usr/scripts/updates-gui
After "Update Now" there should be no cancel button.
X (exit) dialog button should not pop up the Save updates log dialog.
=> Fix gui dialog glitches

usr/scripts/updates-gui, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_updates_gui.policy
added policyconfig for updaes-gui
remove gksu
=> added policyconfig

usr/bin/lite-software, usr/scripts/autologin-d, usr/scripts/autologin-e, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_autologin_d.policy, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_autologin_e.policy, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_software.policy
replace gksu with pkexec lite-software, autologin-e, autologin-d
Minor wording changes
=> policyconfig update

usr/bin/lite-software, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_autologin_d.policy, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_autologin_e.policy, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_cnss_gui.policy, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_software.policy, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_updates_gui.policy
added vendor info to policyconfig
minor code clean up
=> code clean up

usr/scripts/createsysreport, usr/share/doc/lite-software/changelog, usr/share/polkit-1/actions/com.ubuntu.pkexec.lite_createsysreport.policy
new createsysreport with pkexec
HTML generated reports
=> new createsysreport

usr/scripts/autologin-d, usr/scripts/autologin-e
Pipe WARNING **: Couldn't connect to accessibility bus: Failed to
connect to socket to /dev/null for zenity dialogs
=> cleanup output

usr/scripts/cnss-gui, usr/scripts/updates-gui
Cleanup zenity dialogs output
Replace Install Updates plain text dialog with HTML
code cleaned up and reorganize execution
=> cleanup and optimization

usr/bin/lite-software
Clean up zenity output in Lite Software.
clean up code
=> clean output

usr/scripts/createsysreport
=> listing order

usr/scripts/createsysreport
adjust table width so that they are expanded.
=> adjust width

usr/scripts/createsysreport
Adjust text, fields, fonts and dialog sizes.
- Make report text size 100% and reduce size only for Kernel Modules and Software section 80%
Added an extra “Save to Desktop” button to report dialog.
=> createsysreport updated

DEBIAN/postinst
Check files before setting permissions
=> posinst update

DEBIAN/postinst
check directory exist before chmod files within it
=> postinst update

usr/scripts/createsysreport, usr/share/doc/lite-software/changelog
HTML page colors updated.
Fixed page footed dotted line.
=> createsysreport update

usr/share/doc/lite-software/changelog
This reverts commit 1aadd50a54bad795f6d0ed3add2d30f7ce4a6e2b.
=> Revert changelog updated

usr/scripts/updates-gui
add logging for errors while fetching packages cache information lists
=> add logging
